# Site settings
title: Victor Góis
description: Criador Digital | Desenvolvedor | Video Maker | Jornalista | Pesquisador
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://victorgois.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Victor Góis
user_description: Tenho formação em Sistemas de Informação (não concluído) e Comunicação Social, ambas graduações realizadas na Universidade Federal de Minas Gerais (UFMG).
Atuo no segmento tecnológico desde 2013, como desenvolvedor web, tendo desenvolvido nesta trajetória outras competências como marketing digital, design de interfaces (UI),
e produção de conteúdo para web. Hoje atuo como pesquisador no NucCon e desenvolvedor digital freelancer, em Belo Horizonte. Entre meus principais trabalhos recentes
estão o desenvolvimento e webdesign de sites; edição de vídeos; automatização de APIs e raspagem de dados.

Sou apaixonado por experimentar tecnologias, desenvolver competências novas e me comunicar.
Acredito que a comunicação e educação tecnológica tem um papel fundamental para a formação de uma sociedade mais justa e igualitária.

Meus interesses de pesquisa passam por Cibercultura; Jornalismo de Dados; Critical Making e Métodos Digitais.
user_title: Jornalista | Desenvolvedor | Pesquisador
email: victorgois18@gmail.com
twitter_username: victorgoisp
github_username: victorgois
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
