# Site settings
title: Victor Góis 
description: Criador de conteúdo digital | Desenvolvedor | Motion Designer | Video Maker | Jornalista | Pesquisador
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://victorgois.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Victor Góis
user_description: Sou pesquisador e produtor de tecnologia e cultura digital, de Belo Horizonte, Brasil. Atuo com desenvolvimento e webdesign; edição e manipulação audiovisual; jornalismo e visualização de dados; automatização e inteligência de dados. Meus interesses de pesquisa passam por Cibercultura, Jornalismo de Dados, Arte Digital, Estudos críticos de novas mídias, Hackativismo e Transmídia
user_title: Jornalista | Desenvolvedor | Motion Designer
email: victorgois18@gmail.com
twitter_username: victorgoisp
github_username:  victorgois
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
