#-------------------------------
# General Site Settings

menu:
- {name: 'Projetos', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Sobre', url: 'pages/about.html'}
- {name: 'Contato', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Site pessoal de Victor Góis. Desenvolvido com Jekyll e GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Alquimista Digital
  
  Sou pesquisador e produtor de tecnologia e cultura digital, de Belo Horizonte, Brasil.

  Atuo com desenvolvimento e design web; edição e manipulação audiovisual; jornalismo e visualização de dados; big data e inteligência de dados.

  Meus interesses de pesquisa passam por Cibercultura, Jornalismo de Dados, Arte Digital, Estudos críticos de novas mídias, Hackativismo e Transmídia.

  Para mais detalhes profissionais, cheque meu [Linkedin](https://www.linkedin.com/in/victorgoisp/), [Academia](https://ufmg.academia.edu/VictorGóis) e [Lattes](http://lattes.cnpq.br/9758621394268918). 

contact: >
  # Contact

  Você pode entrar em contato comigo [através do meu e-mail](mailto:victorgois18@gmail.com) ou [pelo twitter](https://twitter.com/victorgoisp) se você tiver alguma dúvida ou quiser trocar uma ideia.

#-------------------------------
# Work Section

projects:
- {name: 'Eins', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Três', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Cuatro', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Cinque', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/victorgoisp'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'http://github.com/victorgois'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/victorgoisp/'}
- {icon: 'envelope', link: 'mailto:victorgois18@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
